package br.com.gerador.generator.template;

import br.com.gerador.generator.util.NamingUtils;
import br.com.gerador.metamodel.model.Entity;
import br.com.gerador.metamodel.model.Field;

import java.util.Set;
import java.util.TreeSet;

/**
 * Template para geração de DTOs (Data Transfer Objects).
 */
public class DTOTemplate {

    private final String basePackage;

    public DTOTemplate(String basePackage) {
        this.basePackage = basePackage;
    }

    /**
     * Gera DTO de resposta (Response).
     */
    public String generateResponseDTO(Entity entity) {
        return generateDTO(entity, "Response", false);
    }

    /**
     * Gera DTO de requisição (Request).
     */
    public String generateRequestDTO(Entity entity) {
        return generateDTO(entity, "Request", true);
    }

    /**
     * Verifica se a entidade não tem nenhum campo marcado como PK.
     */
    private boolean hasNoPrimaryKey(Entity entity) {
        return entity.getFields().stream()
            .noneMatch(Field::isPrimaryKey);
    }

    /**
     * Gera DTO de listagem resumida.
     */
    public String generateListDTO(Entity entity) {
        StringBuilder sb = new StringBuilder();
        String entityName = entity.getName();
        Set<String> imports = new TreeSet<>();
        boolean hasNoPk = hasNoPrimaryKey(entity);

        // Coleta imports
        for (Field field : entity.getFields()) {
            if (isVisibleInGrid(field)) {
                String imp = NamingUtils.getImportForType(field.getDataType());
                if (imp != null) {
                    imports.add(imp);
                }
            }
        }

        // Package
        sb.append("package ").append(basePackage).append(".dto;\n\n");

        // Imports
        for (String imp : imports) {
            sb.append("import ").append(imp).append(";\n");
        }
        if (!imports.isEmpty()) {
            sb.append("\n");
        }

        // Javadoc
        sb.append("/**\n");
        sb.append(" * DTO de listagem para ").append(entityName).append(".\n");
        sb.append(" */\n");

        // Record
        sb.append("public record ").append(entityName).append("ListDTO(\n");

        boolean first = true;

        // Se não tem PK, adiciona id artificial
        if (hasNoPk) {
            sb.append("    Long id");
            first = false;
        }

        for (Field field : entity.getFields()) {
            if (isVisibleInGrid(field) || field.isPrimaryKey()) {
                if (!first) {
                    sb.append(",\n");
                }
                String javaType = NamingUtils.toJavaType(field.getDataType());
                sb.append("    ").append(javaType).append(" ").append(field.getName());
                first = false;
            }
        }

        sb.append("\n) {}\n");

        return sb.toString();
    }

    private String generateDTO(Entity entity, String suffix, boolean excludePk) {
        StringBuilder sb = new StringBuilder();
        String entityName = entity.getName();
        Set<String> imports = new TreeSet<>();
        boolean hasNoPk = hasNoPrimaryKey(entity);
        boolean isResponse = "Response".equals(suffix);

        // Coleta imports
        for (Field field : entity.getFields()) {
            if (!excludePk || !isAutoGeneratedPrimaryKey(field)) {
                String imp = NamingUtils.getImportForType(field.getDataType());
                if (imp != null) {
                    imports.add(imp);
                }
            }
        }

        // Adiciona imports de validação
        imports.add("jakarta.validation.constraints.*");

        // Package
        sb.append("package ").append(basePackage).append(".dto;\n\n");

        // Imports
        for (String imp : imports) {
            sb.append("import ").append(imp).append(";\n");
        }
        sb.append("\n");

        // Javadoc
        sb.append("/**\n");
        sb.append(" * DTO de ").append(suffix.toLowerCase()).append(" para ").append(entityName).append(".\n");
        sb.append(" */\n");

        // Record
        sb.append("public record ").append(entityName).append(suffix).append("DTO(\n");

        boolean first = true;

        // Se não tem PK e é Response, adiciona id artificial
        if (hasNoPk && isResponse) {
            sb.append("    Long id");
            first = false;
        }

        for (Field field : entity.getFields()) {
            // Para Request, exclui PKs auto-incrementadas
            if (excludePk && isAutoGeneratedPrimaryKey(field)) {
                continue;
            }

            if (!first) {
                sb.append(",\n");
            }

            // Annotations de validação
            if (field.isRequired() && !field.isPrimaryKey()) {
                sb.append("    @NotNull\n");
                if (NamingUtils.isStringType(field.getDataType())) {
                    sb.append("    @NotBlank\n");
                }
            }
            if (field.getLength() != null && field.getLength() > 0 && NamingUtils.isStringType(field.getDataType())) {
                sb.append("    @Size(max = ").append(field.getLength()).append(")\n");
            }

            String javaType = NamingUtils.toJavaType(field.getDataType());
            sb.append("    ").append(javaType).append(" ").append(field.getName());
            first = false;
        }

        sb.append("\n) {}\n");

        return sb.toString();
    }

    private boolean isVisibleInGrid(Field field) {
        return field.getUi() != null
            && field.getUi().getGrid() != null
            && field.getUi().getGrid().isVisible();
    }

    /**
     * Verifica se um campo é uma PK auto-gerada.
     * Apenas campos explicitamente marcados como autoIncrement são considerados auto-gerados.
     */
    private boolean isAutoGeneratedPrimaryKey(Field field) {
        if (!field.isPrimaryKey()) {
            return false;
        }
        // Apenas se explicitamente marcado como autoIncrement
        return field.isAutoIncrement();
    }
}
