package br.com.gerador.generator.template;

import br.com.gerador.generator.util.NamingUtils;
import br.com.gerador.metamodel.model.Entity;
import br.com.gerador.metamodel.model.Field;

import java.util.List;
import java.util.stream.Collectors;

/**
 * Template para geração de Mapper.
 */
public class MapperTemplate {

    private final String basePackage;

    public MapperTemplate(String basePackage) {
        this.basePackage = basePackage;
    }

    /**
     * Verifica se a entidade tem chave primária composta.
     */
    private boolean hasCompositeKey(Entity entity) {
        long pkCount = entity.getFields().stream()
            .filter(Field::isPrimaryKey)
            .count();
        return pkCount > 1;
    }

    /**
     * Verifica se a entidade não tem nenhum campo marcado como PK.
     */
    private boolean hasNoPrimaryKey(Entity entity) {
        return entity.getFields().stream()
            .noneMatch(Field::isPrimaryKey);
    }

    /**
     * Verifica se o campo é uma chave primária auto-gerada (não deve aparecer no RequestDTO).
     * Apenas campos explicitamente marcados como autoIncrement são considerados auto-gerados.
     */
    private boolean isAutoGeneratedPrimaryKey(Field field) {
        if (!field.isPrimaryKey()) {
            return false;
        }
        return field.isAutoIncrement();
    }

    public String generate(Entity entity) {
        StringBuilder sb = new StringBuilder();
        String entityName = entity.getName();
        boolean hasCompositeKey = hasCompositeKey(entity);
        boolean hasNoPk = hasNoPrimaryKey(entity);

        List<Field> pkFields = entity.getFields().stream()
            .filter(Field::isPrimaryKey)
            .collect(Collectors.toList());

        // Package
        sb.append("package ").append(basePackage).append(".mapper;\n\n");

        // Imports
        sb.append("import ").append(basePackage).append(".dto.*;\n");
        sb.append("import ").append(basePackage).append(".entity.").append(entityName).append(";\n");
        if (hasCompositeKey) {
            sb.append("import ").append(basePackage).append(".entity.").append(entityName).append("Id;\n");
        }
        sb.append("import org.springframework.stereotype.Component;\n");
        sb.append("\n");

        // Javadoc
        sb.append("/**\n");
        sb.append(" * Mapper para conversão entre ").append(entityName).append(" e DTOs.\n");
        sb.append(" */\n");

        // Classe
        sb.append("@Component\n");
        sb.append("public class ").append(entityName).append("Mapper {\n\n");

        // toResponseDTO
        sb.append("    /**\n");
        sb.append("     * Converte Entity para ResponseDTO.\n");
        sb.append("     */\n");
        sb.append("    public ").append(entityName).append("ResponseDTO toResponseDTO(").append(entityName).append(" entity) {\n");
        sb.append("        if (entity == null) {\n");
        sb.append("            return null;\n");
        sb.append("        }\n");
        sb.append("        return new ").append(entityName).append("ResponseDTO(\n");

        boolean first = true;
        // Se não tem PK, adiciona entity.getId() primeiro
        if (hasNoPk) {
            sb.append("            entity.getId()");
            first = false;
        }
        for (Field field : entity.getFields()) {
            if (!first) {
                sb.append(",\n");
            }
            String getter = generateGetter(field, hasCompositeKey);
            sb.append("            ").append(getter);
            first = false;
        }
        sb.append("\n        );\n");
        sb.append("    }\n\n");

        // toListDTO
        sb.append("    /**\n");
        sb.append("     * Converte Entity para ListDTO.\n");
        sb.append("     */\n");
        sb.append("    public ").append(entityName).append("ListDTO toListDTO(").append(entityName).append(" entity) {\n");
        sb.append("        if (entity == null) {\n");
        sb.append("            return null;\n");
        sb.append("        }\n");
        sb.append("        return new ").append(entityName).append("ListDTO(\n");

        first = true;
        // Se não tem PK, adiciona entity.getId() primeiro
        if (hasNoPk) {
            sb.append("            entity.getId()");
            first = false;
        }
        for (Field field : entity.getFields()) {
            if (isVisibleInGrid(field) || field.isPrimaryKey()) {
                if (!first) {
                    sb.append(",\n");
                }
                String getter = generateGetter(field, hasCompositeKey);
                sb.append("            ").append(getter);
                first = false;
            }
        }
        sb.append("\n        );\n");
        sb.append("    }\n\n");

        // toEntity
        sb.append("    /**\n");
        sb.append("     * Converte RequestDTO para Entity.\n");
        sb.append("     */\n");
        sb.append("    public ").append(entityName).append(" toEntity(").append(entityName).append("RequestDTO dto) {\n");
        sb.append("        if (dto == null) {\n");
        sb.append("            return null;\n");
        sb.append("        }\n");
        sb.append("        ").append(entityName).append(" entity = new ").append(entityName).append("();\n");

        if (hasCompositeKey) {
            // Cria o objeto Id e define os campos (apenas PKs não auto-geradas)
            sb.append("        ").append(entityName).append("Id id = new ").append(entityName).append("Id();\n");
            for (Field field : pkFields) {
                // Pula PKs auto-geradas (não existem no RequestDTO)
                if (isAutoGeneratedPrimaryKey(field)) {
                    continue;
                }
                String setter = "id.set" + NamingUtils.toPascalCase(field.getName());
                String getter = "dto." + field.getName() + "()";
                sb.append("        ").append(setter).append("(").append(getter).append(");\n");
            }
            sb.append("        entity.setId(id);\n");
        }

        for (Field field : entity.getFields()) {
            // Pula PKs auto-geradas (não existem no RequestDTO)
            if (isAutoGeneratedPrimaryKey(field)) {
                continue;
            }
            // Pula PKs de chave composta (já tratadas acima)
            if (hasCompositeKey && field.isPrimaryKey()) {
                continue;
            }
            String setter = "entity.set" + NamingUtils.toPascalCase(field.getName());
            String getter = "dto." + field.getName() + "()";
            sb.append("        ").append(setter).append("(").append(getter).append(");\n");
        }
        sb.append("        return entity;\n");
        sb.append("    }\n\n");

        // updateEntity
        sb.append("    /**\n");
        sb.append("     * Atualiza Entity a partir de RequestDTO.\n");
        sb.append("     */\n");
        sb.append("    public void updateEntity(").append(entityName).append("RequestDTO dto, ").append(entityName).append(" entity) {\n");
        sb.append("        if (dto == null || entity == null) {\n");
        sb.append("            return;\n");
        sb.append("        }\n");

        for (Field field : entity.getFields()) {
            // Pula PKs (não atualiza chave primária)
            if (field.isPrimaryKey()) {
                continue;
            }
            String setter = "entity.set" + NamingUtils.toPascalCase(field.getName());
            String getter = "dto." + field.getName() + "()";
            sb.append("        ").append(setter).append("(").append(getter).append(");\n");
        }
        sb.append("    }\n");

        sb.append("}\n");

        return sb.toString();
    }

    /**
     * Gera o getter para um campo, levando em conta se é chave composta.
     */
    private String generateGetter(Field field, boolean hasCompositeKey) {
        String fieldName = NamingUtils.toPascalCase(field.getName());
        if (hasCompositeKey && field.isPrimaryKey()) {
            // Acessa via getId().getField()
            return "entity.getId().get" + fieldName + "()";
        }
        return "entity.get" + fieldName + "()";
    }

    private boolean isVisibleInGrid(Field field) {
        return field.getUi() != null
            && field.getUi().getGrid() != null
            && field.getUi().getGrid().isVisible();
    }
}
